### PR TITLE
Fix open graph tags.

### PR DESCRIPTION
**Pull request by ssylvia**
- Remove extra article tag in title tag.
- Remove "www" from open graph title tag so viewers don't get security warning.

### CODE REVIEW

**Comment by elpinguinodev** [comment]
thanks @ssylvia . ive updated this. the image still doesn't come up though. i also noticed my gitpages url comes up, not the url i have it redirected to christchurchstreetart.co.nz. is there anything i can do about that?
screen shot 2016-10-29 at 9 06 35 am

i also noticed it used to look like this, where the correct url was actually there, so i dont know why it has switched back.
screen shot 2016-10-26 at 7 54 00 pm

**Comment by ssylvia** [comment]
It looks like after you merged my edits, you continued to edit the meta tags which changed the share display. First, the image that you're pointing to is this:
https://christchurchstreetart.co.nz/resources/icons/dcy_welch_thumb.jpg, however, if you try to load the URL in a browser tab, you will get a 404 error because your server does not have an https certificate installed. You'll need to use the http url: http://christchurchstreetart.co.nz/resources/icons/dcy_welch_thumb.jpg. Also, the URL changed because you removed the og:url tag 
`<meta property="og:url" content="http://christchurchstreetart.co.nz" />`
Again, make sure you use the http version because your server does not have a https certificate.

**Comment by elpinguinodev** [comment]
hi @ssylvia , thank you for looking into this. im made the changes, but im still getting the same result. im not sure if it has anything to do with how i'm redirecting the url to christchurchstreetart.co.nz. I'm sure it's something simple, but looks like i've taken on a project that is too far beyond my grasp if i can't even figure this out. i want to share this map all over facebook so people know to use it, but not if the open graph looks like this.

**Comment by elpinguinodev** [comment]
@ssylvia . ive tried doing exactly as you said in your last comment- use http NOT https

ive also tried:
-changing the image
-the image definitely works when i put its file path in the browser
-changing from jpeg to png
-taking out the url line in <meta
-changing the image size after reading the fb image best practice guide

I'm really trying to give it a good go, but I lack the expertise.

**Comment by ssylvia** [comment]
Ok, so I think the problem is your telling Facebook the URL it should display is: http://christchurchstreetart.co.nz/ so Facebook is reading the OpenGraph tags from that page. In order to display the correct description, title, photo; try adding the open graph tags to that page.

**Comment by elpinguinodev** [comment]
@ssylvia . i have added the type, title, description, and photo, to index.html in elpinguinodev.github.io/maptour_user which redirects to http://christchurchstreetart.co.nz. 

this is what i have for the image tag- http://christchurchstreetart.co.nz/resources/icons/owen_ele_big.png. when i put it in the browser it works. 

are you saying it won't work as long as i have the url redirecting?

i am getting these issues.
screen shot 2016-11-04 at 7 06 02 am

i've taken out the url because it wasn't shown in your article. i added it in based off of what i read on the facebook developer website.

i'm also not sure about the facebook app id. there was not mention of it in your article, so i assume it was because you had no issues with it/ did not need to worry about it. is it different for me because i am not hosting it on an arcgis platform?

**Comment by ssylvia** [comment]
Sorry, no what I am saying is because you were embedding the app in this url: http://christchurchstreetart.co.nz and the app had the og:url meta tag point to that url, all the other meta tags must be in the html of: http://christchurchstreetart.co.nz. not in the html of: https://elpinguinodev.github.io/maptour_user/. 

Since you told Facebook to use http://christchurchstreetart.co.nz in the og:url, this is what it reads:

``` html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="description" content="">
<meta name="keywords" content="">
<title>Watch this Space</title>
</head>
<body style="border:0;font-family:inherit;font-size:100%;font-style:inherit;font-weight:inherit;margin:0;outline:0;padding:0;vertical-align:baseline;">
<iframe src="https://elpinguinodev.github.io/maptour_user/" style="width:100%; height:100%; border:none !important; margin:0px !important; padding:0px !important;"/>
</body>
</html>
```

That is why only the old title was coming through. Here's some more information on Open Graph tags for Facebook: https://developers.facebook.com/docs/sharing/webmasters. For the image, try using `og:image:height/width` properties. Also, you can remove the appid unless you want to get additional analytics through Facebook in which case you will need to register your own: https://developers.facebook.com/docs/opengraph/getting-started#create-app.

**Comment by elpinguinodev** [comment]
@ssylvia, does this mean it will be impossible for me to share the open graph with an image until I move the maptour away from gitpages? if i move to amazon web services will this go away?

**Comment by ssylvia** [comment]
No, you just have to add all your open graph tags to the html on this page: http://christchurchstreetart.co.nz, not the gitpages url. The only open graph tag you need on the git page is `og:url`

**Comment by elpinguinodev** [comment]
@ssylvia hey, im not sure if i've been unclear explaining my situation. im using http://christchurchstreetart.co.nz as a cloak to https://elpinguinodev.github.io. i got the image to come up, but only when i changed the file path to https://elpinguinodev.github.io.

what do you mean the tags must be in the html must be in http://christchurchstreetart.co.nz? there is only one index.html which lives in https://elpinguinodev.github.io.

sorry. i know this is basic, and i really appreciate your help. i really want to get this up so i can share it using the proper website, http://christchurchstreetart.co.nz

**Comment by ssylvia** [comment]
Where are you hosting http://christchurchstreetart.co.nz? This URL is the second index.html page. If you go to that URL and right click and select "View Source" you will see the html I posted 4 comments above. The "cloaking" you mentioned is not actually changing the URL of the github page. Instead, you have a second webpage (index.html) at http://christchurchstreetart.co.nz which only contains an iFrame (embedded story) that fills the entire page.

When a user clicks on the facebook share button in the app, the app shares the URL of the github page index.html html. When Facebook scans the meta tags on the github page, it will read the title, description, and image from this page but will keep the URL as the github url because that is where the content is coming from and that is the link Facebook will send viewers to when they click on it.

If you want users to see the "http://christchurchstreetart.co.nz" url on the facebook share and be directed there from facebook then you should use the `og:url` tag. If you use the `og:url` tag, Facebook will ignore the open graph tags on the github page and instead scan the open graph tags on the http://christchurchstreetart.co.nz index.html. Because the only tags in that index.html page is the title, you will only get the title and the correct URL.

There are two solutions:
1. Add the `og:url` meta tag to your github page index.html file and add the rest of the open graph tags (`og:title`, `og:description`, `og:image`) to the http://christchurchstreetart.co.nz index.html that hosts the embedded story. **Ok solution; better if you will use the domain for more than one app.**
2. Add your custom domain to your github page: https://help.github.com/articles/using-a-custom-domain-with-github-pages/. Instead of having an iFrame that embeds your story, this will actually change the url of the github page. **This is a better solution if this domain is only for this app. Embedding apps full screen is not a recommended solution for changing URLs**

**Comment by elpinguinodev** [comment]
@ssylvia , you are the best, seriously. thank you for explaining this to me in a way in so much details. i should have looked at gitpages first to see if i could even host through a custom domain.

New Zealand Tourism is writing an article about my project, and now ill feel confident knowing the maptour can be shared through facebook and have an awesome open graph! im also in talks with Christchurch & Canterbury Tourism who want to embed the map on their website.

Again, I really appreciate your patience, rephrasing and rewording in a way that i could understand. keep posting articles on in the developer's corner i will keep an eye out for them.

**Comment by ssylvia** [comment]
Great! I'm glad I was able to help.

**Pull request merged**
